version: '3'
services:
  common: &BASE
    build:
      context: .
      args:
        - BUNDLE_GITHUB__COM=${BUNDLE_GITHUB__COM}
    env_file:
      - .env.docker

  build:
    <<: *BASE
    command: yarn build

  tests:
    <<: *BASE
    command: yarn test:ci

  voicemails:
    <<: *BASE
    ports:
      - 3000:3000
      - 8080:8080
    networks:
      app_net:
        aliases:
          - lvh.me
          - www.lvh.me
    working_dir: /usr/src/app
    command: npm run serve

  acceptance-base: &ACCEPTANCE_BASE
    build:
      context: .
      args:
        - BUNDLE_GITHUB__COM=${BUNDLE_GITHUB__COM}
    networks:
      - app_net
    depends_on:
      - chrome
    env_file:
      - .env.docker
    working_dir: /usr/src/app

  acceptance-deploy-qa:
    <<: *ACCEPTANCE_BASE
    environment:
      - NODE_ENV=test
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - HUB_PATH=/wd/hub
      - ACCEPTANCE_STAGE=QA
    command: dockerize -wait https://tdagentappstestsqa.trytalkdesk.com/atlas -timeout 90s npm run acceptance -- --suite deploy

  acceptance-deploy-prd:
    <<: *ACCEPTANCE_BASE
    environment:
      - NODE_ENV=test
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - HUB_PATH=/wd/hub
      - ACCEPTANCE_STAGE=PRD
    command: dockerize -wait https://tdagentappstestsprd.mytalkdesk.com/atlas -timeout 90s npm run acceptance -- --suite deploy

  acceptance: &ACCEPTANCE
    <<: *ACCEPTANCE_BASE
    depends_on:
      - chrome
      - voicemails
    environment:
      - NODE_ENV=test
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - HUB_PATH=/wd/hub
    command: dockerize -wait https://www.lvh.me:8080 -timeout 90s npm run acceptance

  acceptance-smoke:
    <<: *ACCEPTANCE
    command: dockerize -wait https://www.lvh.me:8080 -timeout 90s npm run acceptance -- --suite smoke

  acceptance-regression:
    <<: *ACCEPTANCE
    command: dockerize -wait https://www.lvh.me:8080 -timeout 90s npm run acceptance -- --suite regression

  selenium-hub:
    image: selenium/hub:latest
    networks:
      - app_net

  chrome:
    image: selenium/node-chrome:latest
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - app_net
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444

networks:
  app_net:
