version: '3'
services:
  common: &BASE
    # environment:
    #   - REACT_APP_DEMO_DASHBOARD_APP_ID=${REACT_APP_DEMO_DASHBOARD_APP_ID}
    #   - REACT_APP_DEMO_WEBCARD_APP_ID=${REACT_APP_DEMO_WEBCARD_APP_ID}
    build:
      context: .
      args:
        - BUNDLE_GITHUB__COM=${BUNDLE_GITHUB__COM}

  build:
    <<: *BASE
    command: ./scripts/build_packages.sh

  build-stg:
    <<: *BASE
    environment:
      # - REACT_APP_DEMO_DASHBOARD_APP_ID=44a80d22300a4e12a77ddd17cdfb7fb6
      # - REACT_APP_DEMO_WEBCARD_APP_ID=fd77e11decb2413a8256856d2c40c46fk
      - REACT_APP_SDK_URL=https://stg-cdn-talkdesk.talkdeskdev.com/atlas/latest/sdk/index.js
    command: ./scripts/build_packages.sh

  build-qa:
    <<: *BASE
    environment:
      # - REACT_APP_DEMO_DASHBOARD_APP_ID=f36216c1464846ab976abe6567bda070
      # - REACT_APP_DEMO_WEBCARD_APP_ID=3fad451815a74977826412cfedbce2cb
      - REACT_APP_SDK_URL=https://qa-cdn-talkdesk.talkdeskdev.com/atlas/latest/sdk/index.js
    command: ./scripts/build_packages.sh

  build-prd:
    <<: *BASE
    environment:
      # - REACT_APP_DEMO_DASHBOARD_APP_ID=44a80d22300a4e12a77ddd17cdfb7fb6
      # - REACT_APP_DEMO_WEBCARD_APP_ID=fd77e11decb2413a8256856d2c40c46fk
      - REACT_APP_SDK_URL=https://prd-cdn-talkdesk.talkdesk.com/atlas/latest/sdk/index.js
    command: ./scripts/build_packages.sh

  test:
    <<: *BASE
    command: bash -c "yarn test:ci"

  lint:
    <<: *BASE
    command: bash -c "yarn lint"
